unit-tests:
  stage: test
  image: python:3.8-alpine
  before_script:
    - apk add -U build-base openldap-dev python3-dev libffi-dev libressl-dev
    - pip install -r requirements.txt
    - pip install pytest pytest-flask coverage
  script:
    - coverage run -m pytest
    - coverage report -m --include="anyrepo/*"
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
