stages:
  - test
  - build
  - deploy

unit-tests:
  stage: test
  image: python:3.8-alpine
  before_script:
    - apk add -U build-base openldap-dev python3-dev libffi-dev libressl-dev
    - pip install -r requirements.txt
    - pip install pytest pytest-flask coverage
  script:
    - coverage run -m pytest
    - coverage report -m --include="anyrepo/*"
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

.deployment:
  image: registry.anybox.cloud/infra/infra-cli:dev
  variables:
    IMAGE: "$CI_REGISTRY_IMAGE"
    COMMIT_TAG: "$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-$CI_PIPELINE_ID"
  services:
    - docker:18.09.7-dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_ENV_CI_REGISTRY


build_staging:
  extends: .deployment
  stage: build
  script:
    - docker pull $IMAGE:$CI_COMMIT_REF_NAME || true
    - |-
        docker build --cache-from $IMAGE:$CI_COMMIT_REF_NAME \
            --build-arg CONFIG="$CONFIG_STAGING" \
            --tag $IMAGE:$COMMIT_TAG \
            --tag "$IMAGE:$CI_COMMIT_REF_NAME" .
    - docker push "$IMAGE:$COMMIT_TAG"
  only:
    - master

deploy_staging:
  extends: .deployment
  stage: deploy
  environment:
    name: staging
    url: https://$DNS_STAGING
  script:
    - aws_cli create-dns-if-not-exists $DNS_STAGING staging
    - aws_cli create-efs-directory $CI_PROJECT_PATH/$CI_ENVIRONMENT_NAME/db $CI_ENVIRONMENT_NAME
    - envsubst < docker-compose.staging.yml > docker-compose.yml
    - |-
          portainer_cli deploy-stack $PORTAINER_USER $PORTAINER_PASS \
              "$CI_PROJECT_NAMESPACE"_"$CI_PROJECT_NAME" $CI_ENVIRONMENT_NAME \
              docker-compose.yml $GITLAB_USER_LOGIN $CI_PROJECT_NAME
    # tag image
    - docker pull "$CI_REGISTRY_IMAGE:$COMMIT_TAG"
    - |-
          (docker pull "$CI_REGISTRY_IMAGE:staging" && \
              docker tag "$CI_REGISTRY_IMAGE:staging" "$CI_REGISTRY_IMAGE:old-staging" && \
              docker push "$CI_REGISTRY_IMAGE:old-staging" && \
              docker tag "$CI_REGISTRY_IMAGE:$COMMIT_TAG" "$CI_REGISTRY_IMAGE:staging") || \
              (docker tag "$CI_REGISTRY_IMAGE:$COMMIT_TAG" "$CI_REGISTRY_IMAGE:staging")
    - docker push "$CI_REGISTRY_IMAGE:staging"
