- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
    - id: trailing-whitespace
    - id: flake8
    - id: end-of-file-fixer

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.761
  hooks:
    - id: mypy

- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      args: ["-l", "79", "-t", "py38"]

- repo: https://github.com/asottile/seed-isort-config
  rev: v1.9.1
  hooks:
    - id: seed-isort-config

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.20
  hooks:
    - id: isort
