version: '3.7'

services:
  anyrepo:
    image: ${IMAGE}:${COMMIT_TAG}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      labels:
        traefik.port: "8888"
        traefik.backend: "anyrepo"
        traefik.domain.network: "traefik_traefik-net"
        traefik.frontend.rule: "Host:${DNS_STAGING}"
    networks:
      - default
      - traefik_traefik-net


networks:
  default:
  traefik_traefik-net:
    external: true
