version: '3.7'

services:
  anyrepo:
    image: ${IMAGE}:${COMMIT_TAG}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
        labels:
          traefik.port: "8888"
          traefik.backend: "anyrepo"
          traefik.domain.network: "traefik_traefik-net"
          traefik.frontend.rule: "Host:${DNS_STAGING}"
      networks:
        - default
        - traefik_traefik-net

    db:
      image: postgres:12
      volumes:
        - /efs/${CI_PROJECT_PATH}/${CI_ENVIRONMENT_NAME}/db/:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=anyrepo
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - default

networks:
  default:
  traefik_traefik-net:
    external: true
